# This is a basic workflow to help you get started with Actions

name: Get Charts Info

# Controls when the workflow will run
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

env:
  TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN_NORTHWORD_GHOST }}
        run: |
          npm install
          npm run get-chart

      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          path: docs/
          retention-days: 3
