name: Sync repo to Gitee

on:
  workflow_call:
    secrets:
      GITEE_PRIVATE_KEY:
        required: true
      GITEE_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Get current repository name
        id: info
        uses: actions/github-script@v3.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            return context.repo.repo;

      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/zotero-chinese
          src_account_type: org
          dst: gitee/northword
          dst_account_type: user
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "${{ steps.info.outputs.result }}"
          force_update: true
